name: Deploy in master

on:
  push:
    branches:
    - master

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #- uses: actions/setup-python@v2
       # with:
        #  python-version: '3.x'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      #- name: python runtime
       # env:
         # CI: true
       # run: |
        #  npm ci
      - name: deploy
        run: |
          pwd
          ls
          zip -j deploy.zip ./dist/*
          aws lambda create-function --function-name=github-actions-lambda-py --runtime python3.7 --zip-file=fileb://deploy.zip
